name: fluid_box
description: Responsive helper for fluid layout. Allows you to control the layout of children based on constraints and grid.
version: 1.0.0
author: Andy Chentsov <chentsov@gmail.com>
homepage: https://github.com/andyduke/fluid_box/tree/master/package
repository: https://github.com/andyduke/fluid_box
issue_tracker: https://github.com/andyduke/fluid_box/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
